# Generated by Django 6.0.6 on 2026-06-28 21:29

import classes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0002_category_alter_course_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-created_at'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='streamcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='streampost',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Post do Mural', 'verbose_name_plural': 'Posts do Mural'},
        ),
        migrations.AddField(
            model_name='class',
            name='color',
            field=models.CharField(default='#4285f4', max_length=7, verbose_name='Cor da Turma'),
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='streampost',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='stream/attachments/', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='streampost',
            name='link_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='courses.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='class',
            name='join_code',
            field=models.CharField(default=classes.models.generate_join_code, max_length=20, unique=True, verbose_name='Código de Acesso'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da Turma'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('DROPPED', 'Desistente'), ('COMPLETED', 'Concluído')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='streamcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='streamcomment',
            name='content',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='streamcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classes.streampost', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='streampost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='streampost',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='streampost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Fixado'),
        ),
        migrations.AlterField(
            model_name='streampost',
            name='post_type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Aviso'), ('MATERIAL', 'Material'), ('ASSIGNMENT', 'Atividade'), ('MEETING', 'Reunião')], default='ANNOUNCEMENT', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='streampost',
            name='target_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_posts', to='classes.class', verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('CLASS', 'Aula'), ('ASSIGNMENT', 'Entrega de Atividade'), ('EXAM', 'Avaliação'), ('MEETING', 'Reunião'), ('OTHER', 'Outro')], default='CLASS', max_length=15, verbose_name='Tipo')),
                ('start_datetime', models.DateTimeField(verbose_name='Início')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('meeting_url', models.URLField(blank=True, null=True, verbose_name='Link da Reunião')),
                ('color', models.CharField(default='#4285f4', max_length=7)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='classes.class', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('present', models.BooleanField(default=False, verbose_name='Presente')),
                ('justified', models.BooleanField(default=False, verbose_name='Justificado')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.class', verbose_name='Turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.calendarevent', verbose_name='Aula/Evento')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'unique_together': {('enrolled_class', 'student', 'date')},
            },
        ),
    ]

