# Generated by Django 6.0.6 on 2026-07-03 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_class_options_alter_enrollment_options_and_more'),
        ('courses', '0002_category_alter_course_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to='courses.lesson', verbose_name='Aula')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_private_comments', to=settings.AUTH_USER_MODEL, verbose_name='Aluno do Chat Privado')),
            ],
            options={
                'verbose_name': 'Comentário da Aula',
                'verbose_name_plural': 'Comentários da Aula',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_submissions/', verbose_name='Arquivo')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Conteúdo de Texto')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_submissions', to='courses.lesson', verbose_name='Aula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Entrega de Aula',
                'verbose_name_plural': 'Entregas de Aula',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]

