# Generated by Django 6.0.6 on 2026-07-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_lessoncomment_lessonsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Imagem de Banner'),
        ),
    ]

