# Generated by Django 6.0.6 on 2026-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='checkin_open',
            field=models.BooleanField(default=False, verbose_name='Check-in Liberado'),
        ),
    ]

