# Generated by Django 6.0.6 on 2026-07-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_checkin_open'),
        ('courses', '0004_materialfolder_material_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampost',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.materialfolder', verbose_name='Pasta Anexada'),
        ),
    ]
