# Generated by Django 6.0.6 on 2026-07-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_streampost_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='checkin_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in Aberto Em'),
        ),
    ]
