# Generated by Django 6.0.6 on 2026-07-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_class_checkin_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dias da Semana (0=Seg, 1=Ter, etc.)'),
        ),
        migrations.AddField(
            model_name='class',
            name='hours_per_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas por Dia'),
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='class',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Carga Horária Total (horas)'),
        ),
    ]
