# Generated by Django 6.0.6 on 2026-07-19 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_class_days_of_week_class_hours_per_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('content', models.TextField(verbose_name='Anotação / Lembrete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='classes.class', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Anotação da Turma',
                'verbose_name_plural': 'Anotações da Turma',
                'ordering': ['date', '-created_at'],
            },
        ),
    ]
