# Generated by Django 6.0.6 on 2026-08-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_classnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_via',
            field=models.CharField(choices=[('TEACHER', 'Marcado pelo Professor'), ('CHECKIN', 'Check-in pelo Aluno'), ('SYSTEM', 'Sistema')], default='TEACHER', max_length=20, verbose_name='Origem do Registro'),
        ),
    ]
