# Generated by Django 6.0.6 on 2026-09-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_attendance_created_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivada'),
        ),
    ]
