# Generated by Django 6.0.6 on 2026-09-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_add_is_archived_to_class'),
        ('courses', '0005_add_folder_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('FOCUSED', 'Focado 🎯'), ('HAPPY', 'Feliz 😊'), ('SAD', 'Triste 😢'), ('CONFUSED', 'Confuso 😕'), ('TIRED', 'Cansado 😴'), ('EXCITED', 'Animado 🤩')], max_length=20, verbose_name='Estado de Espírito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='courses.lesson', verbose_name='Aula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_moods', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Estado de Espírito',
                'verbose_name_plural': 'Estados de Espírito',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
