# Generated by Django 6.0.6 on 2026-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_lessonmood'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnote',
            name='color',
            field=models.CharField(default='#ffeb3b', max_length=7, verbose_name='Cor'),
        ),
    ]
