# Generated by Django 6.0.6 on 2026-09-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_classnote_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnote',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='classnote',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='classes.class', verbose_name='Turma'),
        ),
    ]
