# Generated by Django 6.0.6 on 2026-09-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_classnote_date_alter_classnote_target_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='banner_alignment',
            field=models.CharField(choices=[('top', 'Topo'), ('center', 'Centro'), ('bottom', 'Fundo')], default='center', max_length=20, verbose_name='Alinhamento do Banner'),
        ),
    ]
