# Generated by Django 6.0.6 on 2026-09-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_class_banner_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='banner_alignment',
            field=models.CharField(default='center', max_length=50, verbose_name='Alinhamento do Banner'),
        ),
    ]
