# Generated by Django 6.0.6 on 2026-07-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_promoted_teacher',
            field=models.BooleanField(default=False, verbose_name='Promovido a Professor'),
        ),
    ]
