# Generated by Django 6.0.6 on 2026-06-28 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='bi-folder', help_text='Bootstrap Icon class', max_length=50)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/qr/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/banners/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Iniciante'), ('INTERMEDIATE', 'Intermediário'), ('ADVANCED', 'Avançado')], default='BEGINNER', max_length=15, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, null=True, verbose_name='Pré-requisitos'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='course',
            name='workload_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga Horária (h)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Duração (min)'),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Código Único'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='workload_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson', verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('VIDEO', 'Vídeo'), ('PDF', 'PDF'), ('LINK', 'Link Externo'), ('FILE', 'Arquivo'), ('SLIDE', 'Slides'), ('AUDIO', 'Áudio')], default='FILE', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.module', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='material',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Categoria'),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='qr_code_url',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='verification_url',
        ),
    ]

