# Generated by Django 6.0.6 on 2026-07-03 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_lessoncomment_lessonsubmission'),
        ('courses', '0002_category_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publicada'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.class', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Módulo'),
        ),
    ]
