# Generated by Django 6.0.6 on 2026-07-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_is_published_lesson_publish_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Pasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='courses.lesson', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Pasta de Material',
                'verbose_name_plural': 'Pastas de Material',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.materialfolder', verbose_name='Pasta'),
        ),
    ]
