# Generated by Django 6.0.6 on 2026-07-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_materialfolder_material_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialfolder',
            name='color',
            field=models.CharField(default='#F5A623', max_length=7, verbose_name='Cor da Pasta'),
        ),
    ]
