# Generated by Django 6.0.6 on 2026-06-28 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('classes', '0002_alter_class_options_alter_enrollment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_late',
            field=models.BooleanField(default=False, verbose_name='Aceitar Entrega Atrasada'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('EXERCISE', 'Exercício'), ('PROJECT', 'Projeto'), ('QUIZ', 'Questionário'), ('EXAM', 'Avaliação'), ('WORK', 'Trabalho')], default='EXERCISE', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/attachments/', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.TextField(blank=True, null=True, verbose_name='Rubrica de Avaliação'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Entrega Atrasada'),
        ),
        migrations.AddField(
            model_name='submission',
            name='return_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário de Devolução'),
        ),
        migrations.AddField(
            model_name='submission',
            name='return_requested',
            field=models.BooleanField(default=False, verbose_name='Devolução Solicitada'),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário do Professor'),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Nota Máxima'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='target_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.class', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to=settings.AUTH_USER_MODEL, verbose_name='Corrigido por'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignments.submission', verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Aluno'),
        ),
    ]
